"""Teaching a computer player to build the units its house has paid for.

A human builds what the sidebar offers, so giving one a private copy of a
unit is enough. A computer player builds what its task forces name, and
those name the original. Buy an upgrade for the ally and nothing changes:
the copy exists, is owned by the right house, and is never asked for.

So the ask has to be rewritten. For every task force that names a bought
unit, this produces a copy naming that house's copy of the unit, and a team
pointing at the new task force.

What decides who builds a copy is not the copy: it is ownership. Of the
1427 team types in the installed file, 1386 are ``Autocreate=yes`` and
every one of them says ``House=<none>`` -- teams for all four sides, with
nothing in them naming a side. An Allied computer player does not spend the
match failing to build Foehn teams, so the engine is choosing autocreate
teams by what the house can actually build. That is the lever: a copy is
gated to one country, so only that house takes it, and the original is shut
out of that country, so that house stops taking the original.

Triggers are the second path to a team and are handled the same way: a copy
per house on that side, owned by its country, and the original stood down
once every house that could have used it has one. Left alone, a trigger
would keep asking for the plain version of a unit the house had paid to
improve, or point a house at a team it can no longer build.

Three measurements from the installed AI file made this cheap:

* 945 of the 1090 trigger conditions look at a **building**, five look at
  anything else. Copying units does not disturb what the AI reacts to.
* Every one of the 1556 script actions takes a numeric argument, so no
  script names a unit and none has to be copied. Copies share them.
* A unit appears in about five task forces (median four), so the work is
  proportional to what was bought rather than to the roster.

Mental Omega already writes country-owned triggers itself -- 610 of the
1090 name a country rather than ``<all>`` -- so this is the file's own
idiom rather than something imposed on it.
"""

from pathlib import Path

from randomizer.core.diagnostics import event as log_event
from randomizer.core.paths import GAME_ROOT

from .mapfile import merge_into_map
from .options import read_ini_sections


AI_FILE_NAME = 'aimo.ini'
# The staged file sits where Ares reads before the archives. The marker is
# the launcher's own: it is what keeps a file we wrote from being read back
# as the installation's, by this launcher or by its authenticity check.
STAGED_AI_PATH = GAME_ROOT / AI_FILE_NAME
RANDOMIZER_RULES_MARKER = '; Generated by Mental Omega Randomizer Launcher'
# Lists whose entries this adds to. Numbered from here so nothing the file
# already lists is renumbered.
LIST_KEY_START = 20000
TASK_FORCES = 'TaskForces'
TEAM_TYPES = 'TeamTypes'
TRIGGER_TYPES = 'AITriggerTypes'
# An AI trigger is one comma-separated row. Only four fields are touched.
TRIGGER_NAME = 0
TRIGGER_TEAM_ONE = 1
TRIGGER_OWNER = 2
TRIGGER_SIDE = 12
TRIGGER_TEAM_TWO = 14
# The last three say whether the trigger is live on easy, medium and hard.
# Setting them to 0 is how an original is stood down in favour of the
# per-house copies that replace it.
TRIGGER_DIFFICULTIES = (15, 16, 17)
TRIGGER_FIELDS = 18

_AI_SECTIONS = None


def installed_ai_sections():
    """Return the AI file the installation actually loads, parsed once.

    A loose ``aimo.ini`` in the game folder outranks the archives, so it is
    what the engine reads and therefore what has to be read here -- except
    one this launcher staged itself, which the extractor already refuses.
    """
    global _AI_SECTIONS
    if _AI_SECTIONS is not None:
        return _AI_SECTIONS
    from randomizer.core.paths import APP_DIR
    from randomizer.ui.cameos import extract_mix_files_sync

    cache = APP_DIR / 'cameo_cache' / AI_FILE_NAME
    if not cache.exists():
        extract_mix_files_sync([(AI_FILE_NAME.upper(), cache)])
    _AI_SECTIONS = read_ini_sections(cache) if cache.exists() else {}
    return _AI_SECTIONS


def side_number(side_id, *, rules=None):
    """Return the number an AI trigger uses for a side.

    The rows carry a side as 1..4 where the rules list them as 0..5, and the
    file agrees with itself: every trigger owned by an Allied country says
    1, every Soviet one says 2. So the number is the side's place in
    ``[Sides]`` plus one, read from the installed rules rather than assumed.
    """
    if rules is None:
        from randomizer.ui.cameos import installed_rules_registry

        _superweapons, rules = installed_rules_registry(synchronous=True)
    order = list((rules or {}).get('Sides') or {})
    for index, name in enumerate(order):
        if str(name).lower() == str(side_id).lower():
            return index + 1
    return 0


def _fields(row):
    return [item.strip() for item in str(row or '').split(',')]


def taskforce_units(body):
    """Return ``{key: (count, unit)}`` for a task force's numbered slots."""
    slots = {}
    for key, value in (body or {}).items():
        if not str(key).isdigit() or ',' not in str(value):
            continue
        count, _, unit = str(value).partition(',')
        slots[key] = (count.strip(), unit.strip().upper())
    return slots


def _index(sections, list_section):
    """Return the ids a list section names, in order."""
    return list((sections.get(list_section) or {}).values())


def _next_keys(sections, list_section, count):
    used = {
        int(key) for key in (sections.get(list_section) or {})
        if str(key).isdigit()
    }
    keys = []
    candidate = LIST_KEY_START
    while len(keys) < count:
        while candidate in used:
            candidate += 1
        used.add(candidate)
        keys.append(str(candidate))
        candidate += 1
    return keys


def _identifier(prefix, counter):
    return f'{prefix}{counter:05d}'


def ai_house_code(houses, *, sections=None, prefix='MOA'):
    """Return the AI-file edits that make each house build its own copies.

    ``houses`` are ``(country, side_index, {unit: clone_id})`` for every
    computer player in the battle, bought units or not: a house that bought
    nothing still needs copies of the triggers this stands down.
    """
    sections = sections if sections is not None else installed_ai_sections()
    houses = [
        (str(country), int(side), dict(units or {}))
        for country, side, units in houses
    ]
    bought = {
        unit for _country, _side, units in houses for unit in units
    }
    if not sections or not bought:
        return {}

    force_ids = _index(sections, TASK_FORCES)
    team_ids = _index(sections, TEAM_TYPES)
    # Which task forces name something that was bought, and which teams and
    # triggers lead to them.
    forces = {
        force for force in force_ids
        if any(
            unit in bought
            for _count, unit in taskforce_units(sections.get(force)).values()
        )
    }
    teams = {
        team for team in team_ids
        if str((sections.get(team) or {}).get('TaskForce', '')) in forces
    }
    triggers = {}
    for key, row in (sections.get(TRIGGER_TYPES) or {}).items():
        fields = _fields(row)
        if len(fields) < TRIGGER_FIELDS:
            continue
        if not (
            fields[TRIGGER_TEAM_ONE] in teams
            or fields[TRIGGER_TEAM_TWO] in teams
        ):
            continue
        if all(fields[slot] == '0' for slot in TRIGGER_DIFFICULTIES):
            # Already off on every difficulty. Copying it would produce a
            # trigger that never fires, and standing it down is a no-op.
            continue
        triggers[key] = fields
    code = {}
    made_forces = []
    made_teams = []
    made_triggers = []
    replaced_triggers = set()
    counter = 0
    for country, side, units in houses:
        # Only this house's copies, and only where it bought something. A
        # house with no purchases reuses the originals it already had.
        force_copy = {}
        for force in sorted(forces):
            body = dict(sections.get(force) or {})
            slots = taskforce_units(body)
            replaced = False
            for key, (count, unit) in slots.items():
                clone = units.get(unit)
                if clone:
                    body[key] = f'{count},{clone}'
                    replaced = True
            if not replaced:
                continue
            counter += 1
            identifier = _identifier(prefix, counter)
            body['Name'] = f'{body.get("Name", force)} {country}'[:64]
            code[identifier] = body
            made_forces.append(identifier)
            force_copy[force] = identifier

        team_copy = {}
        for team in sorted(teams):
            body = dict(sections.get(team) or {})
            source = str(body.get('TaskForce', ''))
            if source not in force_copy:
                continue
            counter += 1
            identifier = _identifier(prefix, counter)
            body['TaskForce'] = force_copy[source]
            body['Name'] = f'{body.get("Name", team)} {country}'[:64]
            code[identifier] = body
            made_teams.append(identifier)
            team_copy[team] = identifier

        for key, fields in triggers.items():
            if int(fields[TRIGGER_SIDE] or 0) != side:
                continue
            owner = fields[TRIGGER_OWNER]
            if owner != '<all>' and owner.lower() != country.lower():
                continue
            row = list(fields)
            row[TRIGGER_OWNER] = country
            for slot in (TRIGGER_TEAM_ONE, TRIGGER_TEAM_TWO):
                row[slot] = team_copy.get(row[slot], row[slot])
            row[TRIGGER_NAME] = f'{row[TRIGGER_NAME]} {country}'[:64]
            counter += 1
            identifier = _identifier(prefix, counter)
            code.setdefault(TRIGGER_TYPES, {})[identifier] = ','.join(row)
            made_triggers.append(identifier)
            replaced_triggers.add(key)

    # The originals stand down -- but only the ones that were replaced. A
    # trigger nobody in this battle could have used keeps its own flags:
    # switching it off would take away behaviour without giving any back,
    # and the point of the copies is that nothing is lost.
    for key in sorted(replaced_triggers):
        row = list(triggers[key])
        for slot in TRIGGER_DIFFICULTIES:
            row[slot] = '0'
        code.setdefault(TRIGGER_TYPES, {})[key] = ','.join(row)

    for list_section, made in (
        (TASK_FORCES, made_forces),
        (TEAM_TYPES, made_teams),
    ):
        if not made:
            continue
        keys = _next_keys(sections, list_section, len(made))
        code[list_section] = dict(zip(keys, made))
    if not made_forces:
        # Nothing this house fields names what it bought. The copies would
        # be sections nobody reads.
        return {}
    # A trigger needs no list entry: [AITriggerTypes] is the definitions.
    log_event(
        'skirmish_ai_code_built',
        houses=len(houses),
        units=len(bought),
        task_forces=len(made_forces),
        teams=len(made_teams),
        triggers=len(made_triggers),
        stood_down=len(replaced_triggers),
    )
    return code


def stage_ai_file(code, *, path=None, sections=None):
    """Write the AI file this battle plays with, and return where it went.

    Ares reads the game folder before the archives, so a complete file has
    to be written rather than a patch: what is staged is the installation's
    own AI file with these edits merged into it, marked as the launcher's so
    nothing reads it back as the installation's own.
    """
    target = Path(path) if path else STAGED_AI_PATH
    if not code:
        remove_staged_ai_file(target)
        return None
    from randomizer.core.paths import APP_DIR

    cache = APP_DIR / 'cameo_cache' / AI_FILE_NAME
    if not cache.exists():
        installed_ai_sections()
    if not cache.exists():
        return None
    text = cache.read_bytes().decode('utf-8', errors='ignore')
    newline = '\r\n' if '\r\n' in text else '\n'
    target.write_bytes(
        (RANDOMIZER_RULES_MARKER + newline + text).encode('utf-8')
    )
    keys = merge_into_map(target, code)
    log_event(
        'skirmish_ai_file_staged',
        sections=len(code),
        keys=keys,
        bytes=target.stat().st_size,
    )
    return target


def remove_staged_ai_file(path=None):
    """Remove the AI file this launcher staged, and only that one."""
    target = Path(path) if path else STAGED_AI_PATH
    if not target.is_file():
        return False
    try:
        with target.open('r', encoding='utf-8', errors='ignore') as handle:
            first = handle.readline()
    except OSError:
        return False
    if not first.startswith(RANDOMIZER_RULES_MARKER):
        # Somebody else's file. A submod's AI is not ours to delete.
        return False
    try:
        target.unlink()
    except OSError:
        return False
    return True
