"""Deploy config-selected custom sidebar images for generated map content."""

import shutil
import struct
import zlib
import binascii
import hashlib
import json
import os
import ctypes
from pathlib import Path

from randomizer.core.paths import APP_DIR, CAMEO_CACHE_DIR, GAME_ROOT, SOURCE_DIR
from randomizer.maps.ini import all_section_value_maps
from randomizer.rewards.definitions import UNIT_SIDEBAR_IMAGES


CUSTOM_ASSET_DIR = APP_DIR / 'assets'
BUNDLED_ASSET_DIR = SOURCE_DIR / 'assets'
SIDEBAR_WIDTH = 60
SIDEBAR_HEIGHT = 48
GENERATED_ART_MARKER = (
    '; Generated by Mental Omega Randomizer Launcher unit cameo overlay'
)
GENERATED_UNIT_CAMEO_ASSETS = UNIT_SIDEBAR_IMAGES
RUNTIME_ASSET_DIR = APP_DIR / 'runtime_assets'
RUNTIME_ASSET_MANIFEST = RUNTIME_ASSET_DIR / 'active_game_root_assets.json'
RUNTIME_ASSET_REQUESTS = RUNTIME_ASSET_DIR / 'requested_assets.json'
RUNTIME_ASSET_LEASE = RUNTIME_ASSET_DIR / 'active_launch_lease.json'


class CustomAssetError(ValueError):
    """Raised when a configured custom image cannot be converted safely."""


def _pid_is_running(pid):
    try:
        pid = int(pid)
    except (TypeError, ValueError):
        return False
    if pid <= 0:
        return False
    if pid == os.getpid():
        return True
    if os.name != 'nt':
        try:
            os.kill(pid, 0)
            return True
        except OSError:
            return False
    process = ctypes.windll.kernel32.OpenProcess(0x1000, False, pid)
    if not process:
        return False
    try:
        exit_code = ctypes.c_ulong()
        return bool(
            ctypes.windll.kernel32.GetExitCodeProcess(
                process, ctypes.byref(exit_code)
            )
            and exit_code.value == 259
        )
    finally:
        ctypes.windll.kernel32.CloseHandle(process)


def _runtime_asset_lease():
    if not RUNTIME_ASSET_LEASE.is_file():
        return {}
    try:
        value = json.loads(RUNTIME_ASSET_LEASE.read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return {}
    return value if isinstance(value, dict) else {}


def _other_live_runtime_asset_owner():
    try:
        owner_pid = int(_runtime_asset_lease().get('owner_pid', 0))
    except (TypeError, ValueError):
        return 0
    return (
        owner_pid
        if owner_pid != os.getpid() and _pid_is_running(owner_pid)
        else 0
    )


def claim_runtime_asset_lease():
    """Reserve temporary root assets against another launcher's cleanup."""
    lease = _runtime_asset_lease()
    try:
        owner_pid = int(lease.get('owner_pid', 0))
    except (TypeError, ValueError):
        owner_pid = 0
    if owner_pid == os.getpid():
        return
    if owner_pid and _pid_is_running(owner_pid):
        raise CustomAssetError(
            'Another launcher process is preparing or running a mission.'
        )
    if RUNTIME_ASSET_LEASE.exists():
        RUNTIME_ASSET_LEASE.unlink()
    RUNTIME_ASSET_DIR.mkdir(parents=True, exist_ok=True)
    try:
        descriptor = os.open(
            RUNTIME_ASSET_LEASE,
            os.O_CREAT | os.O_EXCL | os.O_WRONLY,
        )
    except FileExistsError as exc:
        raise CustomAssetError(
            'Another launcher process is preparing or running a mission.'
        ) from exc
    with os.fdopen(descriptor, 'w', encoding='utf-8') as stream:
        json.dump({'owner_pid': os.getpid()}, stream, indent=2)


def _file_digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _runtime_manifest():
    if not RUNTIME_ASSET_MANIFEST.is_file():
        return {}
    try:
        value = json.loads(RUNTIME_ASSET_MANIFEST.read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return {}
    return value if isinstance(value, dict) else {}


def _write_runtime_manifest(value):
    RUNTIME_ASSET_DIR.mkdir(parents=True, exist_ok=True)
    temporary = RUNTIME_ASSET_MANIFEST.with_suffix('.tmp')
    temporary.write_text(json.dumps(value, indent=2), encoding='utf-8')
    temporary.replace(RUNTIME_ASSET_MANIFEST)


def _request_runtime_asset(path):
    path = Path(path)
    requested = []
    if RUNTIME_ASSET_REQUESTS.is_file():
        try:
            value = json.loads(
                RUNTIME_ASSET_REQUESTS.read_text(encoding='utf-8')
            )
            if isinstance(value, list):
                requested = [str(item) for item in value]
        except (OSError, ValueError):
            pass
    if path.name not in requested:
        requested.append(path.name)
    RUNTIME_ASSET_REQUESTS.write_text(
        json.dumps(requested, indent=2), encoding='utf-8'
    )


def _requested_runtime_asset_paths():
    if not RUNTIME_ASSET_REQUESTS.is_file():
        return []
    try:
        value = json.loads(RUNTIME_ASSET_REQUESTS.read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return []
    if not isinstance(value, list):
        return []
    return [
        RUNTIME_ASSET_DIR / name
        for name in value
        if Path(str(name)).name == str(name)
    ]


def _activate_runtime_assets(paths):
    """Copy staged assets to game root without overwriting installed files."""
    claim_runtime_asset_lease()
    manifest = _runtime_manifest()
    deployed = []
    for source in paths:
        source = Path(source)
        if not source.is_file() or source.parent.resolve() != RUNTIME_ASSET_DIR.resolve():
            continue
        target = GAME_ROOT / source.name
        digest = _file_digest(source)
        if target.exists():
            managed_digest = str(manifest.get(source.name) or '')
            if not (
                target.is_file()
                and _file_digest(target) == digest
                and managed_digest == digest
            ):
                raise CustomAssetError(
                    f'Will not overwrite game-root asset: {target}'
                )
        else:
            shutil.copy2(source, target)
        manifest[source.name] = digest
        deployed.append(target)
    _write_runtime_manifest(manifest)
    return deployed


def remove_generated_runtime_assets():
    """Remove only byte-identical launcher assets temporarily activated at root."""
    if _other_live_runtime_asset_owner():
        return []
    RUNTIME_ASSET_DIR.mkdir(parents=True, exist_ok=True)
    # Recreate old launcher-owned custom PCX outputs in staging so legacy
    # root copies can be proven byte-identical before removal.
    custom_specs = [
        definition for definition in GENERATED_UNIT_CAMEO_ASSETS.values()
        if definition.get('image') and definition.get('pcx')
        and not definition.get('source_pcx')
    ]
    try:
        from randomizer.config.static import load_static_config
        custom_specs.extend(
            {
                'image': config.get('sidebar_image'),
                'pcx': (config.get('values') or {}).get('SidebarPCX'),
            }
            for config in load_static_config(
                'rewards/catalogue.json'
            ).get('aid_power_map_configs', ())
            if config.get('sidebar_image')
        )
    except (OSError, ValueError):
        pass
    for definition in custom_specs:
        try:
            image_name = _asset_name(definition.get('image'), '.png')
            pcx_name = _asset_name(definition.get('pcx'), '.pcx')
            png_to_pcx(
                custom_image_path(image_name), RUNTIME_ASSET_DIR / pcx_name
            )
        except (CustomAssetError, OSError):
            continue
    manifest = _runtime_manifest()
    candidates = dict(manifest)
    if RUNTIME_ASSET_DIR.is_dir():
        for source in RUNTIME_ASSET_DIR.iterdir():
            if source.is_file() and source.name not in {
                RUNTIME_ASSET_MANIFEST.name,
                RUNTIME_ASSET_REQUESTS.name,
                RUNTIME_ASSET_LEASE.name,
            }:
                candidates.setdefault(source.name, _file_digest(source))
    # Older launcher versions extracted installed MIX cameos directly beside
    # the game executable. Exact cache matches are safe legacy cleanup targets.
    for definition in GENERATED_UNIT_CAMEO_ASSETS.values():
        source_name = definition.get('source_pcx')
        if not source_name:
            continue
        name = Path(str(source_name)).name
        cached = CAMEO_CACHE_DIR / name
        if cached.is_file():
            candidates.setdefault(name, _file_digest(cached))
    removed = []
    for name, digest in candidates.items():
        if Path(name).name != name:
            continue
        target = GAME_ROOT / name
        if target.is_file() and _file_digest(target) == str(digest):
            target.unlink()
            removed.append(target)
    if RUNTIME_ASSET_MANIFEST.exists():
        RUNTIME_ASSET_MANIFEST.unlink()
    if RUNTIME_ASSET_REQUESTS.exists():
        RUNTIME_ASSET_REQUESTS.unlink()
    # Staging is disposable. Rebuild only the exact assets requested by the
    # next prepared map, so launcher exit leaves no generated payload behind.
    if RUNTIME_ASSET_DIR.is_dir():
        for source in RUNTIME_ASSET_DIR.iterdir():
            if not source.is_file():
                continue
            try:
                source.unlink()
            except OSError:
                # Another process still has the staged asset open. Staging is
                # disposable and rebuilt per launch, so leaving one file behind
                # must never stop the launcher from starting.
                continue
    return removed


def _configured_cameo_for_art_id(art_id):
    wanted = str(art_id or '').upper()
    direct = GENERATED_UNIT_CAMEO_ASSETS.get(wanted)
    if direct:
        return direct
    matches = [
        definition
        for definition in GENERATED_UNIT_CAMEO_ASSETS.values()
        if str(definition.get('art_id') or '').upper() == wanted
    ]
    # Several custom identities may deliberately clone one installed ArtType.
    # An indirect lookup is safe only when its source ArtType is unambiguous;
    # otherwise it would replace the ordinary unit's cameo with one variant.
    return matches[0] if len(matches) == 1 else None


def _asset_name(value, suffix):
    name = Path(str(value or '')).name
    if not name or name != str(value) or Path(name).suffix.lower() != suffix:
        raise CustomAssetError(f'Custom sidebar asset must be a plain {suffix} filename: {value!r}')
    return name


def custom_image_path(name):
    """Return a visible configured image, copying its bundled default if needed."""
    target = CUSTOM_ASSET_DIR / name
    if target.is_file():
        return target
    bundled = BUNDLED_ASSET_DIR / name
    if not bundled.is_file():
        raise CustomAssetError(f'Custom sidebar image is missing: {target}')
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.resolve() != bundled.resolve():
        shutil.copy2(bundled, target)
    return target


def _paeth(left, above, upper_left):
    estimate = left + above - upper_left
    left_distance = abs(estimate - left)
    above_distance = abs(estimate - above)
    upper_left_distance = abs(estimate - upper_left)
    if left_distance <= above_distance and left_distance <= upper_left_distance:
        return left
    if above_distance <= upper_left_distance:
        return above
    return upper_left


def _decode_png(path):
    data = path.read_bytes()
    if data[:8] != b'\x89PNG\r\n\x1a\n':
        raise CustomAssetError(f'Custom sidebar image is not a PNG: {path}')
    offset = 8
    header = None
    compressed = bytearray()
    while offset + 12 <= len(data):
        length = struct.unpack('>I', data[offset:offset + 4])[0]
        chunk_type = data[offset + 4:offset + 8]
        chunk_data = data[offset + 8:offset + 8 + length]
        if len(chunk_data) != length:
            raise CustomAssetError(f'Truncated PNG chunk in {path}')
        if chunk_type == b'IHDR':
            header = struct.unpack('>IIBBBBB', chunk_data)
        elif chunk_type == b'IDAT':
            compressed.extend(chunk_data)
        elif chunk_type == b'IEND':
            break
        offset += length + 12
    if not header:
        raise CustomAssetError(f'PNG has no IHDR chunk: {path}')
    width, height, depth, color_type, compression, filtering, interlace = header
    if (
        width < 1 or height < 1 or depth != 8 or color_type not in {2, 6}
        or compression != 0 or filtering != 0 or interlace != 0
    ):
        raise CustomAssetError(
            'Custom sidebar PNG must be non-interlaced 8-bit RGB or RGBA'
        )
    channels = 4 if color_type == 6 else 3
    stride = width * channels
    try:
        raw = zlib.decompress(bytes(compressed))
    except zlib.error as exc:
        raise CustomAssetError(f'Cannot decompress custom PNG {path}: {exc}') from exc
    expected = height * (stride + 1)
    if len(raw) != expected:
        raise CustomAssetError(
            f'Unexpected PNG data length in {path}: {len(raw)} instead of {expected}'
        )
    rows = []
    prior = bytearray(stride)
    cursor = 0
    for _ in range(height):
        filter_type = raw[cursor]
        cursor += 1
        encoded = raw[cursor:cursor + stride]
        cursor += stride
        row = bytearray(stride)
        for index, value in enumerate(encoded):
            left = row[index - channels] if index >= channels else 0
            above = prior[index]
            upper_left = prior[index - channels] if index >= channels else 0
            if filter_type == 0:
                predictor = 0
            elif filter_type == 1:
                predictor = left
            elif filter_type == 2:
                predictor = above
            elif filter_type == 3:
                predictor = (left + above) // 2
            elif filter_type == 4:
                predictor = _paeth(left, above, upper_left)
            else:
                raise CustomAssetError(f'Unsupported PNG filter {filter_type} in {path}')
            row[index] = (value + predictor) & 0xFF
        pixels = []
        for index in range(0, stride, channels):
            red, green, blue = row[index:index + 3]
            alpha = row[index + 3] if channels == 4 else 255
            # Game cameos have no alpha plane. Composite transparent pixels on black.
            pixels.append((
                red * alpha // 255,
                green * alpha // 255,
                blue * alpha // 255,
            ))
        rows.append(pixels)
        prior = row
    return width, height, rows


def _resize_cover(width, height, pixels, target_width, target_height):
    source_ratio = width / height
    target_ratio = target_width / target_height
    if source_ratio > target_ratio:
        crop_height = height
        crop_width = height * target_ratio
        crop_x = (width - crop_width) / 2
        crop_y = 0
    else:
        crop_width = width
        crop_height = width / target_ratio
        crop_x = 0
        crop_y = (height - crop_height) / 2
    result = []
    for target_y in range(target_height):
        source_y_start = max(0, int(crop_y + target_y * crop_height / target_height))
        source_y_end = min(
            height,
            max(
                source_y_start + 1,
                int(crop_y + (target_y + 1) * crop_height / target_height + 0.999),
            ),
        )
        row = []
        for target_x in range(target_width):
            source_x_start = max(0, int(crop_x + target_x * crop_width / target_width))
            source_x_end = min(
                width,
                max(
                    source_x_start + 1,
                    int(crop_x + (target_x + 1) * crop_width / target_width + 0.999),
                ),
            )
            samples = [
                pixels[source_y][source_x]
                for source_y in range(source_y_start, source_y_end)
                for source_x in range(source_x_start, source_x_end)
            ]
            sample_count = len(samples)
            row.append(tuple(
                sum(sample[channel] for sample in samples) // sample_count
                for channel in range(3)
            ))
        result.append(row)
    return result


def _pcx_rle(values):
    encoded = bytearray()
    index = 0
    while index < len(values):
        value = values[index]
        run = 1
        while index + run < len(values) and values[index + run] == value and run < 63:
            run += 1
        if run > 1 or value >= 0xC0:
            encoded.extend((0xC0 | run, value))
        else:
            encoded.append(value)
        index += run
    return encoded


def png_to_pcx(source, target):
    width, height, pixels = _decode_png(source)
    pixels = _resize_cover(width, height, pixels, SIDEBAR_WIDTH, SIDEBAR_HEIGHT)
    bytes_per_line = SIDEBAR_WIDTH + (SIDEBAR_WIDTH % 2)
    header = bytearray(128)
    header[0:4] = bytes((10, 5, 1, 8))
    struct.pack_into('<HHHH', header, 4, 0, 0, SIDEBAR_WIDTH - 1, SIDEBAR_HEIGHT - 1)
    struct.pack_into('<HH', header, 12, 72, 72)
    header[64] = 0
    header[65] = 1
    struct.pack_into('<H', header, 66, bytes_per_line)
    struct.pack_into('<H', header, 68, 1)
    body = bytearray(header)
    for row in pixels:
        indices = bytearray(
            ((red >> 5) << 5) | ((green >> 5) << 2) | (blue >> 6)
            for red, green, blue in row
        )
        indices.extend(b'\0' * (bytes_per_line - len(indices)))
        body.extend(_pcx_rle(indices))
    body.append(12)
    for index in range(256):
        body.extend((
            ((index >> 5) & 7) * 255 // 7,
            ((index >> 2) & 7) * 255 // 7,
            (index & 3) * 255 // 3,
        ))
    target.write_bytes(body)
    return target


def deploy_superweapon_sidebar_assets(rewards):
    """Convert active configured PNGs into launcher-owned runtime staging."""
    deployed = []
    seen = set()
    for reward in rewards:
        image_value = reward.get('superweapon_sidebar_image')
        if not image_value:
            continue
        image_name = _asset_name(image_value, '.png')
        rules = reward.get('superweapon_rules') or {}
        pcx_name = _asset_name(rules.get('SidebarPCX'), '.pcx')
        if not pcx_name.lower().startswith('mor'):
            raise CustomAssetError(
                f'Generated sidebar PCX must use the MOR namespace: {pcx_name!r}'
            )
        key = (image_name.lower(), pcx_name.lower())
        if key in seen:
            continue
        seen.add(key)
        source = custom_image_path(image_name)
        RUNTIME_ASSET_DIR.mkdir(parents=True, exist_ok=True)
        target = RUNTIME_ASSET_DIR / pcx_name
        png_to_pcx(source, target)
        _request_runtime_asset(target)
        deployed.append(target)
    return deployed


def _deploy_generated_unit_sidebar_assets(aliases, target_dir, art_text=''):
    """Stage cameo and graphics files used by generated ArtType aliases."""
    requested = {
        str(values.get('CameoPCX') or '').lower()
        for values in aliases.values()
        if isinstance(values, dict)
    }
    deployed = []
    mix_requests = []
    art_sections = _art_cameo_sections(art_text) if art_text else {}
    for unit_id, definition in GENERATED_UNIT_CAMEO_ASSETS.items():
        pcx_value = definition.get('source_pcx') or definition.get('pcx')
        pcx_name = _asset_name(pcx_value, '.pcx')
        if pcx_name.lower() not in requested:
            continue
        if definition.get('source_pcx'):
            target = Path(target_dir) / pcx_name
            mix_requests.append((pcx_name, target))
            deployed.append(target)
        else:
            source = custom_image_path(
                _asset_name(definition['image'], '.png')
            )
            target = Path(target_dir) / pcx_name
            png_to_pcx(source, target)
            deployed.append(target)

        # A unique cameo sometimes requires a unique ArtType even though its
        # unit still uses an installed sprite or voxel. Copy that source asset
        # under the generated ArtType name. Without this, the engine searches
        # for a nonexistent file every frame; infantry becomes invisible and
        # can severely degrade rendering performance.
        source_art_id = str(definition.get('art_id') or '').upper()
        target_art_id = str(unit_id).upper()
        if (
            source_art_id
            and source_art_id != target_art_id
            and target_art_id in aliases
            and target_art_id not in art_sections
        ):
            source_art = art_sections.get(source_art_id, {})
            extensions = (
                ('.vxl', '.hva')
                if str(source_art.get('voxel') or '').lower() == 'yes'
                else ('.shp',)
            )
            for extension in extensions:
                source_name = source_art_id.lower() + extension
                target_name = target_art_id.lower() + extension
                target = Path(target_dir) / target_name
                mix_requests.append((source_name, target))
                deployed.append(target)
    if mix_requests:
        from randomizer.ui.cameos import _extract_mix_files
        extracted = _extract_mix_files(mix_requests)
        missing = [
            source_name
            for source_name, target in mix_requests
            if not Path(target).is_file()
        ]
        if not extracted or missing:
            raise CustomAssetError(
                'Could not extract generated ArtType MIX assets: '
                + (
                    ', '.join(sorted(missing))
                    if missing else 'MIX extraction process failed'
                )
            )
    return deployed


def _art_cameo_sections(text):
    """Read art sections while accepting Mental Omega's trailing comments."""
    sections = {}
    current = None
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if line.startswith('[') and ']' in line:
            current = line[1:line.index(']')].strip().upper()
            sections.setdefault(current, {})
            continue
        if current and line and not line.startswith(';') and '=' in line:
            key, value = line.split('=', 1)
            sections[current][key.strip().lower()] = (
                value.split(';', 1)[0].strip()
            )
    return sections


def _merge_art_section_values(text, section_values):
    """Merge art overrides without shadowing complete installed sections."""
    pending = {
        str(section).upper(): {
            str(key).lower(): (str(key), value)
            for key, value in values.items()
        }
        for section, values in section_values.items()
        if isinstance(values, dict) and values
    }
    lines = text.splitlines()
    output = []
    active = None
    seen_keys = set()
    found_sections = set()

    def flush_missing():
        if active is None:
            return
        for key_lower, (key, value) in pending[active].items():
            if key_lower not in seen_keys and value is not None:
                output.append(f'{key}={value}')

    for line in lines:
        stripped = line.strip()
        if stripped.startswith('[') and ']' in stripped:
            flush_missing()
            section = stripped[1:stripped.index(']')].strip().upper()
            active = (
                section
                if section in pending and section not in found_sections
                else None
            )
            if active is not None:
                found_sections.add(active)
            seen_keys = set()
            output.append(line)
            continue
        if active is not None and '=' in line and not stripped.startswith(';'):
            key_lower = line.split('=', 1)[0].strip().lower()
            replacement = pending[active].get(key_lower)
            if replacement is not None:
                key, value = replacement
                if value is not None:
                    output.append(f'{key}={value}')
                seen_keys.add(key_lower)
                continue
        output.append(line)

    flush_missing()
    for section, values in pending.items():
        if section in found_sections:
            continue
        if output and output[-1].strip():
            output.append('')
        output.append(f'[{section}]')
        output.extend(
            f'{key}={value}'
            for key, value in values.values()
            if value is not None
        )
    return '\n'.join(output) + '\n'


def generated_unit_art_aliases(map_path, art_text):
    """Return art-only cameo aliases required by generated TechnoType IDs."""
    map_sections = all_section_value_maps(
        Path(map_path).read_text(
            encoding='utf-8', errors='ignore'
        ).splitlines()
    )
    map_by_upper = {
        str(section).upper(): values
        for section, values in map_sections.items()
    }
    registered_ids = set()
    for list_name in (
        'INFANTRYTYPES',
        'VEHICLETYPES',
        'AIRCRAFTTYPES',
        'BUILDINGTYPES',
    ):
        for value in map_by_upper.get(list_name, {}).values():
            type_id = str(value).strip().upper()
            if type_id:
                registered_ids.add(type_id)

    art_sections = _art_cameo_sections(art_text)
    aliases = {}
    perun_used = False
    for type_id in sorted(registered_ids):
        values = map_by_upper.get(type_id, {})
        image_id = str(values.get('image') or '').strip().upper()
        if not image_id:
            continue
        name = str(values.get('name') or '').strip().lower()
        perun_used = perun_used or image_id == 'PERUN'
        configured_cameo = _configured_cameo_for_art_id(image_id)
        source_art_id = str(
            (configured_cameo or {}).get('art_id') or image_id
        ).upper()
        source_art = art_sections.get(source_art_id, {})
        cameo = source_art.get('cameopcx')
        alt_cameo = source_art.get('altcameopcx')
        if name == 'jackal racer prototype':
            cameo = 'jackaicon.pcx'
            alt_cameo = 'jackauico.pcx'
        elif configured_cameo:
            cameo = (
                configured_cameo.get('source_pcx')
                or configured_cameo.get('pcx')
            )
            alt_cameo = cameo
        if (
            type_id not in art_sections
            and cameo
        ):
            aliases[type_id] = {
                'CameoPCX': cameo,
                'AltCameoPCX': alt_cameo or cameo,
            }
        # The sidebar reads the ArtType selected by Image=, not necessarily
        # the generated TechnoType section above. Hidden/campaign models often
        # have no installed cameo at all, so a clone-only alias is ignored and
        # the engine displays its purple missing-cameo placeholder. Merge the
        # configured cameo into the complete model art section as well.
        if configured_cameo and cameo:
            aliases[image_id] = {
                **(
                    source_art
                    if image_id != source_art_id
                    and image_id not in art_sections
                    else {}
                ),
                'CameoPCX': cameo,
                'AltCameoPCX': alt_cameo or cameo,
            }
    # PERUN's installed art section supplies the complete voxel but omits its
    # hidden cameo because the campaign identity is normally never buildable.
    # Merge the custom cameo into the complete installed section. Appending a
    # second cameo-only [PERUN] section makes the engine shadow Voxel=yes and
    # renders the unit invisible while leaving its sidebar icon functional.
    if perun_used:
        aliases['PERUN'] = {
            'CameoPCX': GENERATED_UNIT_CAMEO_ASSETS['PERUN']['pcx'],
            'AltCameoPCX': GENERATED_UNIT_CAMEO_ASSETS['PERUN']['pcx'],
        }
        if 'PERUN' not in art_sections:
            aliases['PERUN'].update({
                'Voxel': 'yes',
                'Remapable': 'yes',
            })
    return aliases


def deploy_generated_unit_art(
    map_path,
    target_path=None,
    art_cache_path=None,
):
    """Deploy a complete temporary artmo.ini with generated cameo aliases."""
    runtime_target = Path(target_path or (GAME_ROOT / 'artmo.ini'))
    staged = target_path is None
    target = (
        RUNTIME_ASSET_DIR / 'artmo.ini'
        if staged else runtime_target
    )
    art_cache = Path(art_cache_path or (CAMEO_CACHE_DIR / 'artmo.ini'))
    if not art_cache.is_file():
        raise CustomAssetError(
            f'Installed art cache is missing: {art_cache}'
        )
    if runtime_target.exists():
        first_line = runtime_target.read_text(
            encoding='utf-8', errors='ignore'
        ).splitlines()[:1]
        if first_line != [GENERATED_ART_MARKER]:
            raise CustomAssetError(
                f'Will not replace existing custom art file: {runtime_target}'
            )
    art_text = art_cache.read_text(encoding='utf-8', errors='ignore')
    aliases = generated_unit_art_aliases(map_path, art_text)
    if not aliases:
        if staged:
            _activate_runtime_assets(_requested_runtime_asset_paths())
        else:
            remove_generated_unit_art(target)
        return None, {}
    target.parent.mkdir(parents=True, exist_ok=True)
    unit_assets = _deploy_generated_unit_sidebar_assets(
        aliases,
        RUNTIME_ASSET_DIR if staged else target.parent,
        art_text,
    )
    merged_art = _merge_art_section_values(art_text, aliases)
    target.write_text(
        GENERATED_ART_MARKER + '\n' + merged_art,
        encoding='utf-8',
    )
    if staged:
        deployed = _activate_runtime_assets(
            [target] + _requested_runtime_asset_paths() + unit_assets
        )
        deployed_by_name = {path.name.lower(): path for path in deployed}
        return deployed_by_name.get('artmo.ini'), aliases
    return target, aliases


def remove_generated_unit_art(target_path=None):
    """Remove only the temporary art override created by this launcher."""
    if target_path is None:
        # The generic cleanup path also handles the legacy root art override.
        # Respect another launcher's lease before touching either asset set.
        if _other_live_runtime_asset_owner():
            return False
        removed = remove_generated_runtime_assets()
        legacy_target = GAME_ROOT / 'artmo.ini'
        if legacy_target.is_file():
            first_line = legacy_target.read_text(
                encoding='utf-8', errors='ignore'
            ).splitlines()[:1]
            if first_line == [GENERATED_ART_MARKER]:
                legacy_target.unlink()
                removed.append(legacy_target)
        return bool(removed)
    target = Path(target_path or (GAME_ROOT / 'artmo.ini'))
    if not target.is_file():
        return False
    first_line = target.read_text(
        encoding='utf-8', errors='ignore'
    ).splitlines()[:1]
    if first_line != [GENERATED_ART_MARKER]:
        return False
    target.unlink()
    return True


def _png_chunk(kind, payload):
    return (
        struct.pack('>I', len(payload))
        + kind
        + payload
        + struct.pack('>I', binascii.crc32(kind + payload) & 0xFFFFFFFF)
    )


def custom_sidebar_preview(image_value):
    """Return a launcher-ready 60x48 PNG derived from a configured asset."""
    image_name = _asset_name(image_value, '.png')
    source = custom_image_path(image_name)
    target = CAMEO_CACHE_DIR / f'custom-{Path(image_name).stem.lower()}.png'
    if target.is_file() and target.stat().st_mtime_ns >= source.stat().st_mtime_ns:
        return target
    width, height, pixels = _decode_png(source)
    pixels = _resize_cover(width, height, pixels, SIDEBAR_WIDTH, SIDEBAR_HEIGHT)
    scanlines = b''.join(
        b'\0' + bytes(channel for pixel in row for channel in pixel)
        for row in pixels
    )
    png = (
        b'\x89PNG\r\n\x1a\n'
        + _png_chunk(
            b'IHDR',
            struct.pack('>IIBBBBB', SIDEBAR_WIDTH, SIDEBAR_HEIGHT, 8, 2, 0, 0, 0),
        )
        + _png_chunk(b'IDAT', zlib.compress(scanlines, level=9))
        + _png_chunk(b'IEND', b'')
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(png)
    return target
