"""Regenerate configs/RandomizerUnits.ini -- the list of cloned units.

This used to bake all 494 KB of ``configs/Randomizer*.ini``: every player
clone's complete stat line, copied from stock Mental Omega with the reviewed
clone policy applied. The policy lives in
``randomizer/rewards/template_policy.py`` and the launcher now applies it at
load to the rules the installation actually loads, which reproduced all 326
baked sections with no differences and made the bake dead weight -- worse than
dead, since it froze a submod's units at stock values in the shop.

What could not be derived is which units get a clone at all, and that is what
this writes. Registry slot numbers are preserved across runs: a saved profile
names clones rather than slots, but a stable file keeps regeneration diffs
readable.

    python tools/generate_randomizer_units.py

The other committed roster file, ``RandomizerMapOnlySources.ini``, holds the
six bodies that exist only inside campaign, challenge and cooperative maps and
so cannot be looked up in any rules file. It is maintained by hand from those
maps -- verbatim sections, no policy applied, since the launcher applies it --
and changes about once per Mental Omega release.
"""

from __future__ import annotations

import argparse
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

DEFAULT_OUTPUT = ROOT / 'configs' / 'RandomizerUnits.ini'
# Reviewed infantry the mapper listed for later catalogue expansion. Present
# in the registry so their clone identities stay reserved even before a reward
# points at them.
DEFAULT_INFANTRY = ROOT / 'InfantryList.txt'

TYPE_LISTS = OrderedDict((
    ('infantry', 'InfantryTypes'),
    ('units', 'VehicleTypes'),
    ('aircraft', 'AircraftTypes'),
    ('defenses', 'BuildingTypes'),
    ('special_buildings', 'BuildingTypes'),
))
LIST_ORDER = ('InfantryTypes', 'VehicleTypes', 'AircraftTypes', 'BuildingTypes')
FIRST_KEYS = {
    'InfantryTypes': 300000,
    'VehicleTypes': 320000,
    'AircraftTypes': 340000,
    'BuildingTypes': 350000,
}

HEADER = """; Which units the randomizer clones, and nothing else about them.
;
; Every clone body is built at load from the rules the installation actually
; loads, so a submod's Rhino reaches the game as the submod's Rhino. What
; cannot be derived is the decision of *which* units get a player-owned copy:
; that is reviewed, it is this file, and randomizer_unit_roster() checks it
; against the reward catalogue on every load so the two cannot drift apart.
;
; The numbers are TechnoType registry slots. They are stable across
; regeneration on purpose -- a saved profile names clones, not slots -- and
; carry no other meaning.
;
; Generated by tools/generate_randomizer_units.py; bodies for the six units
; that exist only inside maps live in RandomizerMapOnlySources.ini."""


def read_sections(path):
    sections = OrderedDict()
    current = None
    for raw_line in path.read_text(encoding='utf-8-sig').splitlines():
        stripped = raw_line.strip()
        if stripped.startswith('[') and stripped.endswith(']'):
            current = stripped[1:-1].strip()
            sections[current] = OrderedDict()
            continue
        if current is None or not stripped or stripped.startswith(';'):
            continue
        if '=' not in raw_line:
            continue
        key, value = raw_line.split('=', 1)
        sections[current][key.strip()] = value.split(';', 1)[0].strip()
    return sections


def previous_slots(path):
    """Return ``{list: {CLONE_ID: slot}}`` from the committed file."""
    if not path.is_file():
        return {}
    slots = {}
    for section, values in read_sections(path).items():
        name = next(
            (item for item in LIST_ORDER if item.lower() == section.lower()),
            None,
        )
        if not name:
            continue
        for key, clone_id in values.items():
            if str(key).isdigit() and str(clone_id).upper().startswith('MORP'):
                slots.setdefault(name, {})[str(clone_id).upper()] = int(key)
    return slots


def reviewed_extra_infantry(path):
    """Return reviewed clone ids from the mapper's InfantryList.txt."""
    if not path.is_file():
        return []
    sections = read_sections(path)
    registry = next(
        (
            values for section, values in sections.items()
            if section.lower() == 'infantrytypes'
        ),
        {},
    )
    extra = []
    for clone_id in registry.values():
        clone_id = str(clone_id).strip().upper()
        if clone_id.startswith('MORP'):
            extra.append(clone_id[4:])
        elif clone_id == 'MORE1':
            extra.append('E1')
    return extra


def clone_ids_by_list(reviewed_extra, previous):
    from randomizer.rewards.catalogue import BUFF_TARGETS

    by_list = OrderedDict((name, []) for name in LIST_ORDER)
    seen = set()

    def add(list_name, source_id):
        source_id = str(source_id).upper()
        if source_id in seen:
            return
        seen.add(source_id)
        by_list[list_name].append(source_id)

    # Already committed wins, always. A clone id that leaves this file leaves
    # a saved profile pointing at a unit that no longer exists, and the ones
    # here now include reviewed identities the catalogue does not yet name.
    for list_name, known in previous.items():
        for clone_id in known:
            add(list_name, clone_id[4:])
    for source_id, target in BUFF_TARGETS.items():
        list_name = TYPE_LISTS.get(target.get('category'))
        if not list_name:
            continue
        # Deploy/undeploy forms are cloned from live rules at launch and are
        # not separate buildable identities; only reviewed historical ones
        # keep a registry slot, and those are already committed above.
        if target.get('runtime_transform') or target.get('power_payload_only'):
            continue
        add(list_name, source_id)
    for source_id in reviewed_extra:
        add('InfantryTypes', source_id)
    return by_list


def assign_slots(by_list, previous):
    """Return ``[(list, slot, clone_id)]`` keeping committed slots put."""
    rows = []
    for list_name in LIST_ORDER:
        known = previous.get(list_name, {})
        used = set(known.values())
        entries = []
        # A slot the committed file never handed out; only new units take one.
        next_key = max([FIRST_KEYS[list_name] - 1, *used]) + 1
        for source_id in by_list.get(list_name, ()):
            clone_id = 'MORP' + source_id
            slot = known.get(clone_id)
            if slot is None:
                while next_key in used:
                    next_key += 1
                slot = next_key
                used.add(slot)
                next_key += 1
            entries.append((slot, clone_id))
        rows.extend(
            (list_name, slot, clone_id)
            for slot, clone_id in sorted(entries)
        )
    return rows


def build(destination, infantry_path):
    previous = previous_slots(destination)
    rows = assign_slots(
        clone_ids_by_list(reviewed_extra_infantry(infantry_path), previous),
        previous,
    )
    lines = [HEADER]
    for list_name in LIST_ORDER:
        entries = [row for row in rows if row[0] == list_name]
        if not entries:
            continue
        lines.append('')
        lines.append('[{}]'.format(list_name))
        lines.extend(
            '{}={}'.format(slot, clone_id) for _list, slot, clone_id in entries
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print('{}: {} clone(s), {:.1f} KB'.format(
        destination, len(rows), destination.stat().st_size / 1024
    ))
    return rows


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--infantry', type=Path, default=DEFAULT_INFANTRY)
    args = parser.parse_args(argv)
    build(args.output, args.infantry)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
